"use client";

import React from "react";
import { useRouter } from "next/navigation";
import {
  Shield,
  CheckCircle,
  Clock,
  XCircle,
  ExternalLink,
  Loader2,
  LogOut,
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import { useProofHistoryAuth } from "../hooks/useProofHistoryAuth";

export function ProofHistory() {
  const router = useRouter();
  const { proofs, isLoading, error, isAuthenticated, refreshProofs } =
    useProofHistoryAuth();

  const getProofTypeLabel = (type: string) => {
    switch (type) {
      case "spending_authorization":
        return "Spending Authorization";
      case "identity_in_group":
        return "Identity in Group";
      case "solvency":
        return "Solvency Proof";
      case "compliance":
        return "Compliance Check";
      default:
        return type;
    }
  };

  const getProofTypeColor = (type: string) => {
    switch (type) {
      case "spending_authorization":
        return "bg-purple-900/20 text-purple-400";
      case "identity_in_group":
        return "bg-blue-900/20 text-blue-400";
      case "solvency":
        return "bg-emerald-900/20 text-emerald-400";
      case "compliance":
        return "bg-yellow-900/20 text-yellow-400";
      default:
        return "bg-zinc-900/20 text-zinc-400";
    }
  };

  const getRelativeTime = (date: Date) => {
    const now = new Date();
    const diff = now.getTime() - date.getTime();

    const minutes = Math.floor(diff / (1000 * 60));
    const hours = Math.floor(diff / (1000 * 60 * 60));

    if (minutes < 60) return `${minutes}m ago`;
    return `${hours}h ago`;
  };

  if (!isAuthenticated) {
    return (
      <div className="max-w-5xl mx-auto space-y-8 pb-20">
        <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-12 text-center">
          <LogOut className="h-16 w-16 text-zinc-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-white mb-2">
            Not Authenticated
          </h2>
          <p className="text-zinc-400 mb-6">
            Please login to view proof history.
          </p>
          <Button onClick={() => router.push("/login")}>Go to Login</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-20">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">
            Proof History
          </h1>
          <p className="text-zinc-500">
            All zero-knowledge proofs generated by your session.
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={refreshProofs}
          disabled={isLoading}
        >
          {isLoading ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Shield className="mr-2 h-4 w-4" />
          )}
          Refresh
        </Button>
      </div>

      {error && (
        <div className="rounded-xl bg-red-900/10 border border-red-900/20 p-4">
          <p className="text-sm text-red-400">{error}</p>
        </div>
      )}

      {/* Proof History Table */}
      <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 overflow-hidden">
        <table className="w-full text-left text-sm text-zinc-400">
          <thead className="bg-zinc-900 text-zinc-500">
            <tr>
              <th className="px-6 py-3 font-medium">Proof ID</th>
              <th className="px-6 py-3 font-medium">Type</th>
              <th className="px-6 py-3 font-medium">Timestamp</th>
              <th className="px-6 py-3 font-medium">Status</th>
              <th className="px-6 py-3 font-medium text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800">
            {isLoading ? (
              // Loading skeleton
              Array.from({ length: 5 }).map((_, i) => (
                <tr key={i} className="hover:bg-zinc-800/50 transition-colors">
                  <td className="px-6 py-4">
                    <div className="h-4 w-24 bg-zinc-800/50 rounded animate-pulse"></div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="h-6 w-32 bg-zinc-800/50 rounded-full animate-pulse"></div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="h-4 w-20 bg-zinc-800/50 rounded animate-pulse"></div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="h-6 w-20 bg-zinc-800/50 rounded-full animate-pulse"></div>
                  </td>
                  <td className="px-6 py-4"></td>
                </tr>
              ))
            ) : proofs.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-6 py-12 text-center">
                  <Shield className="h-12 w-12 text-zinc-600 mx-auto mb-3" />
                  <p className="text-zinc-400">No proofs generated yet</p>
                  <p className="text-xs text-zinc-600 mt-1">
                    Proofs will appear here as you interact with the protocol
                  </p>
                </td>
              </tr>
            ) : (
              proofs.map((proof) => (
                <tr
                  key={proof.id}
                  className="hover:bg-zinc-800/50 transition-colors"
                >
                  <td className="px-6 py-4">
                    <code className="text-xs text-zinc-300 font-mono">
                      {proof.id.slice(0, 8)}...
                    </code>
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getProofTypeColor(
                        proof.type
                      )}`}
                    >
                      {getProofTypeLabel(proof.type)}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-zinc-400">
                    {getRelativeTime(proof.timestamp)}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      {proof.status === "verified" ? (
                        <>
                          <CheckCircle className="h-4 w-4 text-emerald-500" />
                          <span className="text-emerald-500 text-xs font-medium">
                            Verified
                          </span>
                        </>
                      ) : proof.status === "pending" ? (
                        <>
                          <Clock className="h-4 w-4 text-yellow-500" />
                          <span className="text-yellow-500 text-xs font-medium">
                            Pending
                          </span>
                        </>
                      ) : (
                        <>
                          <XCircle className="h-4 w-4 text-red-500" />
                          <span className="text-red-500 text-xs font-medium">
                            Failed
                          </span>
                        </>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-right">
                    {proof.txHash && proof.blockExplorer && (
                      <a
                        href={`${proof.blockExplorer}${proof.txHash}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 transition-colors"
                      >
                        View
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Info Card */}
      <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-6">
        <h3 className="text-lg font-semibold text-white mb-4">
          About Zero-Knowledge Proofs
        </h3>
        <div className="space-y-3 text-sm text-zinc-400">
          <p>
            <strong className="text-zinc-300">Privacy-Preserving:</strong> ZK
            proofs allow you to prove statements about your identity, assets, or
            actions without revealing the underlying data.
          </p>
          <p>
            <strong className="text-zinc-300">Verifiable:</strong> Each proof is
            cryptographically verifiable on-chain, ensuring trust without
            compromising privacy.
          </p>
          <p>
            <strong className="text-zinc-300">Session-Based:</strong> Proofs are
            tied to your ephemeral session, not a permanent on-chain identity.
          </p>
        </div>
      </div>
    </div>
  );
}
